

export interface ExerciseDetails {
  name: string;
  type?: string;
  muscle: string;
  equipment?: string;
  difficulty?: string;
  instructions?: string;
  injury_prevention?: string;
  sets?: string;
  reps?: string;
  rest?: string;
  image?: string;
  gifUrl?: string; // Keep for backward compatibility if needed, but prefer image
}

export interface DayWorkout {
  focus: string;
  exercises: ExerciseDetails[];
  gender?: 'male' | 'female';
  location?: 'gym' | 'home';
  day?: string;
}

export interface WorkoutSplit {
  [day: string]: DayWorkout;
}

export interface CustomWorkoutPlan {
  id: string;
  name: string;
  description: string;
  days: Record<string, CustomExercise[]>;
}

export interface CustomExercise extends ExerciseDetails {
  customSets: string;
  customReps: string;
  customRest: string;
}

const defaultExerciseProps = {
  type: "",
  muscle: "",
  equipment: "",
  difficulty: "",
  instructions: "",
  image: "/images/exercises/placeholder.png", // Default placeholder
  injury_prevention: "Always warm up before starting and listen to your body. Stop if you feel sharp pain.",
};

const slugify = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');

const createImagePath = (name: string) => `/images/exercises/${slugify(name)}.png`;


// Add injury prevention tips here
export const MASTER_EXERCISE_DATA: { [key: string]: Partial<ExerciseDetails> } = {
    // Chest
    "Bench Press": { type: 'strength', muscle: 'Chest', equipment: 'Barbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your feet flat on the floor and avoid arching your back excessively. Use a spotter for heavy lifts.' },
    "Push-Ups": { type: 'strength', muscle: 'Chest', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your body in a straight line from head to heels. Lower your chest to the floor in a controlled manner.' },
    "Incline Bench Press": { type: 'strength', muscle: 'Chest', equipment: 'Barbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Do not let the dumbbells or barbell bounce off your chest. Control the weight throughout the movement.' },
    "Dumbbell Flyes": { type: 'strength', muscle: 'Chest', equipment: 'Dumbbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep a slight bend in your elbows and focus on squeezing your chest muscles. Avoid using a weight that is too heavy.' },
    "Cable Crossover": { type: 'strength', muscle: 'Chest', equipment: 'Cable', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Adjust the pulleys to the correct height and maintain a stable stance. Focus on the chest contraction.' },
    "Decline Push-Ups": { type: 'strength', muscle: 'Chest', equipment: 'Bodyweight', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Place your feet securely on the elevated surface. Keep your core engaged to prevent your back from sagging.' },
    "Incline Dumbbell Press": { type: 'strength', muscle: 'Chest', equipment: 'Dumbbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Ensure the bench is at a 30-45 degree angle. Dont arch your back off the bench.' },
    "Chest Dips": { type: 'strength', muscle: 'Chest', equipment: 'Parallel Bars', difficulty: 'advanced', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Lean your torso forward to target the chest more effectively. Lower yourself until you feel a good stretch, but not pain in your shoulders.' },
    "Flat Dumbbell Press": { type: 'strength', muscle: 'Chest', equipment: 'Dumbbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your wrists straight and directly above your elbows. Control the dumbbells throughout the movement.' },
    "Pec Deck Machine": { type: 'strength', muscle: 'Chest', equipment: 'Machine', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Set the seat height so the handles are at chest level. Avoid letting the weights slam at the end of the movement.' },
    "Wall Push-Ups": { type: 'strength', muscle: 'Chest', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Stand far enough from the wall to create a challenge but maintain control. Keep your back straight.' },
    "Wide-Grip Push-Ups": { type: 'strength', muscle: 'Chest', equipment: 'Bodyweight', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Placing your hands wider than your shoulders can put more stress on the shoulder joints. Listen to your body and dont go too wide if it causes discomfort.' },

    // Back
    "Pull-Ups": { type: 'strength', muscle: 'Back', equipment: 'Pull-up Bar', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Avoid swinging or using momentum. Start from a full hang and pull your chin over the bar. Use assistance bands if needed.' },
    "Deadlifts": { type: 'strength', muscle: 'Back', equipment: 'Barbell', difficulty: 'advanced', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your back straight throughout the lift. Hinge at your hips and keep the bar close to your body. Start light to master the form.' },
    "Barbell Rows": { type: 'strength', muscle: 'Back', equipment: 'Barbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Maintain a flat back throughout the movement. Hinge at the hips, and avoid using your lower back to lift the weight.' },
    "Lat Pulldowns": { type: 'strength', muscle: 'Back', equipment: 'Cable', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Pull the bar down to your upper chest, not behind your neck. Avoid using momentum by leaning back too far.' },
    "Seated Cable Row": { type: 'strength', muscle: 'Back', equipment: 'Cable', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your back straight and pull the handle towards your torso, squeezing your shoulder blades together.' },
    "Superman Hold": { type: 'strength', muscle: 'Back', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Lift your arms and legs gently. Avoid arching your back too aggressively, especially if you have lower back issues.' },
    "Inverted Rows": { type: 'strength', muscle: 'Back', equipment: 'Bar/Table', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your body in a straight line. The more horizontal your body, the harder the exercise. Start with a more vertical angle.' },
    "Back Extensions": { type: 'strength', muscle: 'Back', equipment: 'Hyperextension Bench', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Move in a slow, controlled manner. Avoid over-extending (arching) your back at the top of the movement.' },

    // Legs
    "Squats": { type: 'strength', muscle: 'Legs', equipment: 'Bodyweight/Barbell', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your chest up, back straight, and go to a depth that is comfortable for your mobility. Ensure your knees track over your toes.' },
    "Lunges": { type: 'strength', muscle: 'Legs', equipment: 'Bodyweight/Dumbbell', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Take controlled steps and ensure your front knee does not go past your toes. Keep your torso upright.' },
    "Romanian Deadlifts": { type: 'strength', muscle: 'Hamstrings', equipment: 'Barbell/Dumbbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep a slight bend in your knees and maintain a flat back. Hinge at the hips and lower the weight until you feel a stretch in your hamstrings.' },
    "Calf Raises": { type: 'strength', muscle: 'Calves', equipment: 'Bodyweight/Machine', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Perform the movement slowly, focusing on a full range of motion. Avoid bouncing at the bottom.' },
    "Leg Press": { type: 'strength', muscle: 'Legs', equipment: 'Machine', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Do not lock out your knees at the top of the movement. Keep your lower back and hips pressed against the seat.' },
    "Hip Thrusts": { type: 'strength', muscle: 'Glutes', equipment: 'Barbell/Dumbbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Position the bench under your shoulder blades. Keep your chin tucked and focus on using your glutes to lift the weight.' },
    "Glute Bridges": { type: 'strength', muscle: 'Glutes', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Squeeze your glutes at the top of the movement and avoid over-arching your lower back.' },
    "Jump Squats": { type: 'plyometrics', muscle: 'Legs', equipment: 'Bodyweight', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Land softly on the balls of your feet and immediately bend your knees to absorb the impact.' },
    "Bulgarian Split Squats": { type: 'strength', muscle: 'Legs', equipment: 'Dumbbell/Bodyweight', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your torso upright and your front foot flat on the ground. Dont let your front knee travel too far past your toes.' },
    "Box Jumps": { type: 'plyometrics', muscle: 'Legs', equipment: 'Box', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Start with a low box. Land softly on the box and step down, do not jump down, to protect your joints.' },
    
    // Shoulders
    "Shoulder Press": { type: 'strength', muscle: 'Shoulders', equipment: 'Dumbbell/Barbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your core tight to avoid arching your back. Press the weight directly overhead, not in front or behind your head.' },
    "Lateral Raises": { type: 'strength', muscle: 'Shoulders', equipment: 'Dumbbell', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Use a light weight and lead with your elbows. Avoid using momentum or shrugging your traps.' },
    "Front Raises": { type: 'strength', muscle: 'Shoulders', equipment: 'Dumbbell/Plate', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Lift the weight only to shoulder height. Keep your core engaged to prevent leaning back.' },
    "Face Pulls": { type: 'strength', muscle: 'Shoulders', equipment: 'Cable', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Use a lighter weight and focus on external rotation of the shoulders. Pull the rope towards your face, not your neck.' },
    "Shrugs": { type: 'strength', muscle: 'Traps', equipment: 'Dumbbell/Barbell', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Avoid rolling your shoulders. Lift them straight up towards your ears and slowly lower them down.' },
    "Pike Push-ups": { type: 'strength', muscle: 'Shoulders', equipment: 'Bodyweight', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your head in a neutral position, looking towards your feet, not up. This helps protect your neck.' },
    "Arnold Press": { type: 'strength', muscle: 'Shoulders', equipment: 'Dumbbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Perform the rotation smoothly and with control. Avoid using a weight that is too heavy, which can strain the rotator cuff.' },

    // Arms
    "Dumbbell Curl": { type: 'strength', muscle: 'Biceps', equipment: 'Dumbbell', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Avoid swinging the dumbbells. Keep your upper arms stationary and focus on using your biceps to lift the weight.' },
    "Hammer Curl": { type: 'strength', muscle: 'Biceps', equipment: 'Dumbbell', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your palms facing each other and control the movement on the way up and down to protect the elbow joint.' },
    "Triceps Pushdown": { type: 'strength', muscle: 'Triceps', equipment: 'Cable', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your elbows tucked into your sides and avoid using momentum to move the weight.' },
    "Skull Crushers": { type: 'strength', muscle: 'Triceps', equipment: 'Barbell/Dumbbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Lower the weight towards your forehead in a controlled manner. Dont let your elbows flare out too much.' },
    "Overhead Extension": { type: 'strength', muscle: 'Triceps', equipment: 'Cable/Dumbbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your core tight to protect your lower back. Avoid flaring your elbows out.' },
    "Close-Grip Push-Ups": { type: 'strength', muscle: 'Triceps', equipment: 'Bodyweight', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Place your hands closer than shoulder-width apart. Keep your elbows tucked in close to your body as you lower yourself.' },
    "Chin-Ups": { type: 'strength', muscle: 'Biceps', equipment: 'Pull-up Bar', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Use a full range of motion. An underhand grip will target the biceps more, but can also strain the elbows if form is incorrect.' },

    // Core
    "Plank": { type: 'strength', muscle: 'Core', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your back flat and avoid letting your hips sag to prevent lower back strain. Engage your core and glutes.' },
    "Crunches": { type: 'strength', muscle: 'Core', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Avoid pulling on your neck with your hands. Place your hands across your chest or lightly by your head. Lift your shoulders off the floor.' },
    "Leg Raises": { type: 'strength', muscle: 'Core', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Press your lower back into the floor to avoid arching it. If this is difficult, start with bent-knee raises.' },
    "Russian Twists": { type: 'strength', muscle: 'Core', equipment: 'Bodyweight/Medicine Ball', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your back straight and rotate from your torso, not just your arms. Keep the movement controlled.' },
    "Hanging Leg Raises": { type: 'strength', muscle: 'Core', equipment: 'Pull-up Bar', difficulty: 'advanced', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Avoid swinging. Control the movement using your core strength. Start with hanging knee raises if straight-leg raises are too difficult.' },
    "Side Plank": { type: 'strength', muscle: 'Core', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your body in a straight line from your head to your feet. Dont let your hips sag.' },
    "Bicycle Crunches": { type: 'strength', muscle: 'Core', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Go slowly and focus on the twisting motion. Bring your knee towards the opposite elbow, not the other way around.' },
    
    // Cardio / Full Body
    "Jumping Jacks": { type: 'cardio', muscle: 'Full Body', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Land softly on the balls of your feet to reduce impact on your knees and ankles.' },
    "Burpees": { type: 'cardio', muscle: 'Full Body', equipment: 'Bodyweight', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Maintain control throughout the movement. Dont let your back sag during the plank portion.' },
    "Mountain Climbers": { type: 'cardio', muscle: 'Full Body', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your core engaged and your back flat. Bring your knees towards your chest in a controlled running motion.' },
    "Kettlebell Swings": { type: 'strength', muscle: 'Full Body', equipment: 'Kettlebell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'This is a hip hinge movement, not a squat. Use the power from your hips and glutes to swing the kettlebell, not your arms.' },
    "Battle Ropes": { type: 'cardio', muscle: 'Full Body', equipment: 'Battle Ropes', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Maintain a stable athletic stance. The motion should come from your entire body, not just your arms.' },
    "High Knees": { type: 'cardio', muscle: 'Full Body', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Land softly on the balls of your feet. Keep your core engaged and drive your knees up towards your chest.' },

    // Warmup & Flexibility
    "Wrist Roll": { type: 'warmup', muscle: 'Forearms', equipment: 'Wrist Roller', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Use a light weight and perform the movement slowly and in a controlled manner to avoid straining your wrist tendons.' },
    "Elbow Circles": { type: 'warmup', muscle: 'Shoulders', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep the circles smooth and controlled; avoid jerky movements.' },
    "Arm Circles": { type: 'warmup', muscle: 'Shoulders', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Start with small circles and gradually increase the size to warm up the shoulder joint gently.' },
    "Bar Hanging": { type: 'strength', muscle: 'Back', equipment: 'Pull-up Bar', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Engage your shoulder muscles to support your weight; do not hang passively to avoid over-stressing the joints.' },
    "Quad Stretch": { type: 'flexibility', muscle: 'Quads', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Hold onto something for balance and avoid pulling your heel too forcefully. Keep your knees close together.' },
    "Hamstring Stretch": { type: 'flexibility', muscle: 'Hamstrings', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep a slight bend in your knee and avoid rounding your back to protect your spine.' },
    "Chest Stretch": { type: 'flexibility', muscle: 'Chest', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Perform the stretch gently. Do not force your arms back, to prevent shoulder impingement.' },
    "Shoulder Stretch": { type: 'flexibility', muscle: 'Shoulders', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Do not pull your arm across your body too hard. Keep your shoulder down and relaxed.' },
    "Triceps Stretch": { type: 'flexibility', muscle: 'Triceps', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Gently pull your elbow behind your head; avoid forcing the stretch if you feel any shoulder pain.' },
    "Child\'s Pose": { type: 'flexibility', muscle: 'Back', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'If you have knee issues, place a blanket under your shins for cushioning. Breathe deeply to relax your back.' },

    // More exercises to fill out the list
    "Dumbbell Pullover": { type: 'strength', muscle: 'Chest', equipment: 'Dumbbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep a slight bend in your elbows and ensure your lower back stays on the bench. Use a lighter weight to master the form.' },
    "Single Arm Dumbbell Row": { type: 'strength', muscle: 'Back', equipment: 'Dumbbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your back flat and parallel to the floor. Pull the dumbbell towards your hip, not straight up.' },
    "T-Bar Row": { type: 'strength', muscle: 'Back', equipment: 'T-Bar Row Machine', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your chest up and back straight. Avoid using excessive momentum to lift the weight.' },
    "Good Mornings": { type: 'strength', muscle: 'Hamstrings', equipment: 'Barbell', difficulty: 'advanced', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Start with a very light weight or just the bar. Hinge at the hips while maintaining a straight back. This exercise requires excellent form.' },
    "Barbell Hip Thrust": { type: 'strength', muscle: 'Glutes', equipment: 'Barbell', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Position the bench under your shoulder blades. Keep your chin tucked and focus on using your glutes to lift the weight.' },
    "Goblet Squats": { type: 'strength', muscle: 'Legs', equipment: 'Kettlebell/Dumbbell', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep the weight close to your chest and your back straight. This helps maintain an upright torso.' },
    "Cable Kickbacks": { type: 'strength', muscle: 'Glutes', equipment: 'Cable', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your core engaged to avoid arching your back. Focus on squeezing the glute of the working leg.' },
    "Sled Push": { type: 'strength', muscle: 'Full Body', equipment: 'Sled', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Maintain a straight line from your head to your heels. Drive through your legs.' },
    "Push Press": { type: 'strength', muscle: 'Shoulders', equipment: 'Barbell', difficulty: 'advanced', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Use your legs to initiate the drive. Keep the bar path straight up. Dont lean back excessively.' },
    "Clean and Jerk": { type: 'strength', muscle: 'Full Body', equipment: 'Barbell', difficulty: 'advanced', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'This is a highly technical lift. Seek coaching to learn proper form to prevent injury.' },
    "Snatch": { type: 'strength', muscle: 'Full Body', equipment: 'Barbell', difficulty: 'advanced', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Requires significant mobility and technique. It is crucial to learn this from a qualified coach.' },
    "Medicine Ball Slams": { type: 'plyometrics', muscle: 'Full Body', equipment: 'Medicine Ball', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Use your core to slam the ball down, not just your arms. Keep your back straight.' },
    "Treadmill Sprints": { type: 'cardio', muscle: 'Legs', equipment: 'Treadmill', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Build up your speed gradually. Use the safety clip in case you lose your footing.' },
    "Yoga Flow": { type: 'flexibility', muscle: 'Full Body', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Move with your breath and dont force any poses. Listen to your body’s limitations.' },
    "Foam Rolling": { type: 'flexibility', muscle: 'Full Body', equipment: 'Foam Roller', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Roll slowly over tight muscles. Avoid rolling directly over joints or bones.' },
    "Agility Ladder Drills": { type: 'cardio', muscle: 'Full Body', equipment: 'Agility Ladder', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Stay on the balls of your feet and keep your movements quick and light to prevent tripping.' },
    "Cone Sprints": { type: 'cardio', muscle: 'Legs', equipment: 'Cones', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Ensure you have a clear, non-slip surface. Warm up properly before sprinting.' },
    "Side Shuffles": { type: 'cardio', muscle: 'Legs', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Stay low in an athletic stance and push off your outside foot. Dont cross your feet over.' },
    "Jump Rope": { type: 'cardio', muscle: 'Full Body', equipment: 'Jump Rope', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Turn the rope with your wrists, not your whole arms. Land softly on the balls of your feet.' },
    "Power Cleans": { type: 'strength', muscle: 'Full Body', equipment: 'Barbell', difficulty: 'advanced', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'This is a technical lift. Focus on explosive hip extension. Master the form before adding significant weight.' },
    "Ab Roller": { type: 'strength', muscle: 'Core', equipment: 'Ab Wheel', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Keep your core tight and avoid arching your back. Only roll out as far as you can maintain a straight back.' },
    "Assault Bike Intervals": { type: 'cardio', muscle: 'Full Body', equipment: 'Assault Bike', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Set up the bike correctly for your height. Push and pull with both your arms and legs.' },
    "Reaction Ball Drill": { type: 'cardio', muscle: 'Full Body', equipment: 'Reaction Ball', difficulty: 'intermediate', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Use in an open space to avoid collisions. This drill improves hand-eye coordination.' },
    "Shadow Badminton": { type: 'cardio', muscle: 'Full Body', equipment: 'Bodyweight', difficulty: 'beginner', gifUrl: "https://placehold.co/400x400.png", injury_prevention: 'Focus on proper footwork and swing mechanics. Ensure you have enough space around you.' },
    "Decline / Cable Fly": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "triceps pushdown": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Overhead Extension (Cable or Dumbbell)": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Underhand triceps pushdown": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Straight arm Lat Pulldowns": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Ez Barbell Curl": { type: "strength", muscle: "Biceps", gifUrl: "https://placehold.co/400x400.png" },
    "Dumbbell Chest Press": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Tricep Pushdowns": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Reverse Crunches": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Plank Side Holds": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Stretching / Foam rolling": { type: "flexibility", muscle: "Full Body", gifUrl: "https://placehold.co/400x400.png" },
    "Optional: Yoga class": { type: "flexibility", muscle: "Full Body", gifUrl: "https://placehold.co/400x400.png" },
    "Overhead Triceps Extensions": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Superman Pulls": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Isometric Hold": { type: "strength", muscle: "Full Body", gifUrl: "https://placehold.co/400x400.png" },
    "Wrist Curls": { type: "strength", muscle: "Forearms", gifUrl: "https://placehold.co/400x400.png" },
    "Forearm Squeeze": { type: "strength", muscle: "Forearms", gifUrl: "https://placehold.co/400x400.png" },
    "Plank to Push-Up": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Heel Touches": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Light Yoga": { type: "flexibility", muscle: "Full Body", gifUrl: "https://placehold.co/400x400.png" },
    "Stretching": { type: "flexibility", muscle: "Full Body", gifUrl: "https://placehold.co/400x400.png" },
    "20-30 min walk": { type: "cardio", muscle: "Full Body", gifUrl: "https://placehold.co/400x400.png" },
    "Incline Chest Press": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Chest Fly": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Triceps Rope Pushdown": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Overhead DB Triceps Extension": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Lat Pulldown": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Assisted Pull-Ups": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Dumbbell Bicep Curls": { type: "strength", muscle: "Biceps", gifUrl: "https://placehold.co/400x400.png" },
    "Cable Bicep Curls": { type: "strength", muscle: "Biceps", gifUrl: "https://placehold.co/400x400.png" },
    "Smith Squats": { type: "strength", muscle: "Legs", gifUrl: "https://placehold.co/400x400.png" },
    "DB Shoulder Press": { type: "strength", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Flat DB Bench": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Plank Hold": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Cable Oblique Twists": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "T-Bar Rows": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Wide Lat Pulldown": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Concentration Curls": { type: "strength", muscle: "Biceps", gifUrl: "https://placehold.co/400x400.png" },
    "Wrist Curls & Ext": { type: "strength", muscle: "Forearms", gifUrl: "https://placehold.co/400x400.png" },
    "Leg Curls": { type: "strength", muscle: "Hamstrings", gifUrl: "https://placehold.co/400x400.png" },
    "Cable Crunch + Twists": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Stretch / Foam Roll": { type: "flexibility", muscle: "Full Body", gifUrl: "https://placehold.co/400x400.png" },
    "Yoga (Optional)": { type: "flexibility", muscle: "Full Body", gifUrl: "https://placehold.co/400x400.png" },
    "Knee Push-Ups": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Bench Dips": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Triceps Kickbacks": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Superwoman Hold": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Snow Angels": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Wall Angels": { type: "strength", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Forearm Plank": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Bent Over Dumbbell Reverse Flys": { type: "strength", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Wrist Circles": { type: "warmup", muscle: "Forearms", gifUrl: "https://placehold.co/400x400.png" },
    "Sumo Squats": { type: "strength", muscle: "Legs", gifUrl: "https://placehold.co/400x400.png" },
    "Step-Ups": { type: "strength", muscle: "Legs", gifUrl: "https://placehold.co/400x400.png" },
    "Donkey Kicks": { type: "strength", muscle: "Glutes", gifUrl: "https://placehold.co/400x400.png" },
    "Bird Dog": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Walk 20-30 mins": { type: "cardio", muscle: "Full Body", gifUrl: "https://placehold.co/400x400.png" },
    "Flat Barbell Bench Press": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Decline Bench Press": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Chest Press Machine": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Dumbbell Pullover": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Push-Up (Chest Focus)": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Decline Push-Ups": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Wide Arm Push-Ups": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Chest Dips (Chair)": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Explosive Push-Ups": { type: "plyometrics", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Incline Chest Press (Machine or DB)": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Pec Deck Machine": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Flat Dumbbell Press": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Incline Cable Fly": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Incline Push-Ups (Bench/Chair)": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Dumbbell Floor Press (If available)": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Chest Squeeze (with Towel)": { type: "strength", muscle: "Chest", gifUrl: "https://placehold.co/400x400.png" },
    "Inverted Rows (using table)": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Prone Cobra": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Single Arm Dumbbell Row": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Back Extensions (Hyperextensions)": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Prone Arm Lifts (Y-T-W)": { type: "strength", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Cat-Cow Stretch": { type: "flexibility", muscle: "Back", gifUrl: "https://placehold.co/400x400.png" },
    "Barbell Curls": { type: "strength", muscle: "Biceps", gifUrl: "https://placehold.co/400x400.png" },
    "Overhead Cable Extension": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Resistance Band Curls": { type: "strength", muscle: "Biceps", gifUrl: "https://placehold.co/400x400.png" },
    "Overhead Triceps Extensions (Backpack/Weight)": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Hammer Curls (Water Bottles/Dumbbells)": { type: "strength", muscle: "Biceps", gifUrl: "https://placehold.co/400x400.png" },
    "Wrist Squeezes (Towel/Stress Ball)": { type: "strength", muscle: "Forearms", gifUrl: "https://placehold.co/400x400.png" },
    "Cable Triceps Pushdowns": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Incline Hammer Curls": { type: "strength", muscle: "Biceps", gifUrl: "https://placehold.co/400x400.png" },
    "Overhead Water Bottle Extensions": { type: "strength", muscle: "Triceps", gifUrl: "https://placehold.co/400x400.png" },
    "Hammer Curls (Water Bottles)": { type: "strength", muscle: "Biceps", gifUrl: "https://placehold.co/400x400.png" },
    "Reverse Band Curls": { type: "strength", muscle: "Biceps", gifUrl: "https://placehold.co/400x400.png" },
    "Cable Rope Crunch": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Roman Chair Sit-Ups": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Weighted Russian Twists": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Decline Crunch": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Hanging Knee Tucks": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Bicycle Crunches": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Side Plank (Both Sides)": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Seated Ab Machine Crunch": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Decline Sit-Ups": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Stability Ball Pass": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Flutter Kicks": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Side Plank Hip Dips": { type: "strength", muscle: "Core", gifUrl: "https://placehold.co/400x400.png" },
    "Shoulder Press (Barbell or Dumbbell)": { type: "strength", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Lateral Arm Circles (Small + Big)": { type: "warmup", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Elevated Pike Hold": { type: "strength", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Dumbbell Shoulder Press": { type: "strength", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Wall Walks": { type: "strength", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Lateral Arm Raises (Using Water Bottles/Bands)": { type: "strength", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Rear Delt Pulses (Bodyweight or Light Weights)": { type: "strength", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Front Raises (Bottles/Bands)": { type: "strength", muscle: "Shoulders", gifUrl: "https://placehold.co/400x400.png" },
    "Leg Curl Machine": { type: "strength", muscle: "Hamstrings", gifUrl: "https://placehold.co/400x400.png" },
    "Standing Calf Raises": { type: "strength", muscle: "Calves", gifUrl: "https://placehold.co/400x400.png" },
    "Single-Leg Calf Raises": { type: "strength", muscle: "Calves", gifUrl: "https://placehold.co/400x400.png" },
    "Seated Calf Raises": { type: "strength", muscle: "Calves", gifUrl: "https://placehold.co/400x400.png" },
    "Side-Lying Leg Raises": { type: "strength", muscle: "Glutes", gifUrl: "https://placehold.co/400x400.png" },
    "Glute Bridge March": { type: "strength", muscle: "Glutes", gifUrl: "https://placehold.co/400x400.png" },
  "Jawline Sharper (Massage Along Jaw)": { muscle: 'Jaw', image: "/images/exercises/jawline-sharper.png" },
  'Vowel Mouth Stretch ("O"-"E")': { muscle: 'Face', image: "/images/exercises/vowel-mouth-stretch.png" },
  "Lion's Breath": { muscle: 'Face', image: "/images/exercises/lions-breath.png" },
  "Chin Tuck": { muscle: 'Neck', image: "/images/exercises/chin-tuck.png" },
  "Jaw Unlocker": { muscle: 'Jaw', image: "/images/exercises/jaw-unlocker.png" },
  "Cheek & Jawline Lifter": { muscle: 'Cheeks', image: "/images/exercises/cheek-jawline-lifter.png" },
  "Gua Sha or Facial Massage (Jawline)": { muscle: 'Jaw', image: "/images/exercises/gua-sha-massage.png" },
  'Kiss the Ceiling / "Whistler"': { muscle: 'Neck', image: "/images/exercises/kiss-the-ceiling.png" },
  "Lip Trills": { muscle: 'Vocal Cords', image: "/images/exercises/lip-trills.png" },
  "Humming Warm-Up": { muscle: 'Vocal Cords', image: "/images/exercises/humming-warm-up.png" },
  "Sirens (Low to High Pitch Glide)": { muscle: 'Vocal Cords', image: "/images/exercises/sirens.png" },
  "Sustain Note (Deep Chest Voice)": { muscle: 'Vocal Cords', image: "/images/exercises/sustain-note.png" },
  "Consonant Articulation (P-T-K-B-D-G)": { muscle: 'Lips, Tongue', image: "/images/exercises/consonant-articulation.png" },
  "Breath Control (Inhale 4s – Hold – Exhale 8s)": { muscle: 'Diaphragm', image: "/images/exercises/breath-control.png" },
  "Deep 'Ahh' Vowel Projection": { muscle: 'Vocal Cords', image: "/images/exercises/deep-ahh-projection.png" },
  "Lip Bubbles (Trills with Sound)": { muscle: 'Vocal Cords', image: "/images/exercises/lip-bubbles.png" },
  "Humming Glide (Nasal Resonance)": { muscle: 'Vocal Cords', image: "/images/exercises/humming-glide.png" },
  "Octave Sirens (Smooth Pitch Slide)": { muscle: 'Vocal Cords', image: "/images/exercises/octave-sirens.png" },
  "Sustain 'Ee' / 'Oo' Notes": { muscle: 'Vocal Cords', image: "/images/exercises/sustain-ee-oo.png" },
  "Vowel Chains (AEIOU transitions)": { muscle: 'Lips, Tongue', image: "/images/exercises/vowel-chains.png" },
  "Breath Support Drill (4-4-8 breathing)": { muscle: 'Diaphragm', image: "/images/exercises/breath-support-drill.png" },
  "Vocal Stretch (Soft Yawns + 'Haa')": { muscle: 'Vocal Cords', image: "/images/exercises/vocal-stretch.png" },
  "Wall Slides": { muscle: 'Shoulders, Back', image: "/images/exercises/wall-slides.png" },
  "Glute Kickbacks (Bodyweight or Band)": { muscle: 'Glutes', image: "/images/exercises/glute-kickbacks.png" },
  "Reverse Snow Angels (on floor)": { muscle: 'Back', image: "/images/exercises/reverse-snow-angels.png" },
  "Seated Chin Tucks": { muscle: 'Neck', image: "/images/exercises/seated-chin-tucks.png" },
  "Child’s Pose with Reach": { muscle: 'Back, Shoulders', image: "/images/exercises/childs-pose-reach.png" },
  "Butterfly Stretch": { muscle: 'Hips', image: "/images/exercises/butterfly-stretch.png" },
  "Barbell Hip Thrusts": { muscle: 'Glutes', image: "/images/exercises/barbell-hip-thrusts.png" },
  "Cable Pull-Throughs": { muscle: 'Glutes, Hamstrings', image: "/images/exercises/cable-pull-throughs.png" },
  "Kettlebell Swings": { muscle: 'Glutes, Hamstrings', image: "/images/exercises/kettlebell-swings.png" },
  "Standing Cable Hip Flexion": { muscle: 'Hips', image: "/images/exercises/standing-cable-hip-flexion.png" },
  "Controlled Box Jumps": { muscle: 'Legs', image: "/images/exercises/controlled-box-jumps.png" },
  "Bodyweight Glute Bridges": { muscle: 'Glutes', image: "/images/exercises/bodyweight-glute-bridges.png" },
  "Pelvic Tilts": { muscle: 'Core, Pelvic Floor', image: "/images/exercises/pelvic-tilts.png" },
  "Fire Hydrants": { muscle: 'Hips, Glutes', image: "/images/exercises/fire-hydrants.png" },
  "Sumo Deadlifts": { muscle: 'Glutes, Hamstrings, Quads', image: "/images/exercises/sumo-deadlifts.png" },
  "Cable Abductions": { muscle: 'Hips, Glutes', image: "/images/exercises/cable-abductions.png" },
  "Weighted Glute Bridges": { muscle: 'Glutes', image: "/images/exercises/weighted-glute-bridges.png" },
  "Stability Ball Plank": { muscle: 'Core', image: "/images/exercises/stability-ball-plank.png" },
  "Box Jumps": { muscle: "Legs", type: "plyometrics", image: "/images/exercises/box-jumps.png"},
  "Walking Lunges with Dumbbells": { muscle: "Legs", type: "strength", image: "/images/exercises/walking-lunges-dumbbells.png"},
  "Overhead Press (Dumbbells)": { muscle: "Shoulders", type: "strength", image: "/images/exercises/overhead-press-dumbbells.png"},
  "Triceps Pushdowns (Rope)": { muscle: "Triceps", type: "strength", image: "/images/exercises/triceps-pushdowns-rope.png"},
  "Medicine Ball Rotational Slams": { muscle: "Core", type: "power", image: "/images/exercises/medicine-ball-rotational-slams.png"},
  "Foam Rolling (Full Body)": { muscle: "Full Body", type: "flexibility", image: "/images/exercises/foam-rolling-full-body.png"},
  "Yoga Flow (Hamstrings + Back)": { muscle: "Full Body", type: "flexibility", image: "/images/exercises/yoga-flow-hamstrings-back.png"},
  "Light Rowing": { muscle: "Full Body", type: "cardio", image: "/images/exercises/light-rowing.png"},
  "Lateral Bounds": { muscle: "Legs", type: "plyometrics", image: "/images/exercises/lateral-bounds.png"},
  "Agility Ladder Drills": { muscle: "Full Body", type: "agility", image: "/images/exercises/agility-ladder-drills.png"},
  "Single-Leg Deadlifts": { muscle: "Hamstrings", type: "strength", image: "/images/exercises/single-leg-deadlifts.png"},
  "Treadmill Sprints": { muscle: "Full Body", type: "cardio", image: "/images/exercises/treadmill-sprints.png"},
  "Pull-Ups (Weighted if possible)": { muscle: "Back", type: "strength", image: "/images/exercises/pull-ups-weighted.png"},
  "Bent Over Rows": { muscle: "Back", type: "strength", image: "/images/exercises/bent-over-rows.png"},
  "Battle Ropes": { muscle: "Full Body", type: "conditioning", image: "/images/exercises/battle-ropes.png"},
  "Dumbbell Thrusters": { muscle: "Full Body", type: "strength", image: "/images/exercises/dumbbell-thrusters.png"},
  "Sled Push": { muscle: "Full Body", type: "strength", image: "/images/exercises/sled-push.png"},
  "Ab Rollouts": { muscle: "Core", type: "strength", image: "/images/exercises/ab-rollouts.png"},
  "Farmer's Carry": { muscle: "Full Body", type: "strength", image: "/images/exercises/farmers-carry.png"},
  "Goblet Squats": { muscle: "Legs", type: "strength", image: "/images/exercises/goblet-squats.png"},
  "Lateral Band Walks": { muscle: "Glutes", type: "strength", image: "/images/exercises/lateral-band-walks.png"},
  "Incline Dumbbell Press": { muscle: "Chest", type: "strength", image: "/images/exercises/incline-dumbbell-press.png"},
  "Triceps Rope Pushdowns": { muscle: "Triceps", type: "strength", image: "/images/exercises/triceps-rope-pushdowns.png"},
  "Cable Woodchoppers": { muscle: "Core", type: "strength", image: "/images/exercises/cable-woodchoppers.png"},
  "Yoga Flow (Pigeon, Down Dog, Cobra)": { muscle: "Full Body", type: "flexibility", image: "/images/exercises/yoga-flow-pigeon-down-dog-cobra.png"},
  "Light Cycling/ Walking": { muscle: "Full Body", type: "cardio", image: "/images/exercises/light-cycling-walking.png"},
  "Medicine Ball Slams": { muscle: "Full Body", type: "power", image: "/images/exercises/medicine-ball-slams.png"},
  "Bicep Curls": { type: "strength", muscle: "Biceps", image: "/images/exercises/bicep-curls.png"},
  "Dumbbell Walking Lunges": { muscle: "Legs", type: "strength", image: "/images/exercises/dumbbell-walking-lunges.png"},
  "Wall Ball Throws": { muscle: "Full Body", "type": "power", image: "/images/exercises/wall-ball-throws.png"},
  "Single-Leg Calf Raises": { muscle: "Calves", "type": "strength", image: "/images/exercises/single-leg-calf-raises.png"},
  "Plank to Push-Up": { muscle: "Core", "type": "strength", image: "/images/exercises/plank-to-push-up.png"},
  "Agility Ladder (Simulated)": { muscle: "Full Body", "type": "agility", image: "/images/exercises/agility-ladder-simulated.png"},
  "Side-to-Side Bounds": { muscle: "Legs", "type": "plyometrics", image: "/images/exercises/side-to-side-bounds.png"},
  "Reaction Ball or Wall Catch": { muscle: "Full Body", "type": "coordination", image: "/images/exercises/reaction-ball-wall-catch.png"},
  "Shadow Fielding": { muscle: "Full Body", "type": "coordination", image: "/images/exercises/shadow-fielding.png"},
  "Bodyweight Squats": { muscle: "Legs", "type": "strength", image: "/images/exercises/bodyweight-squats.png"},
  "Reverse Lunges": { muscle: "Legs", "type": "strength", image: "/images/exercises/reverse-lunges.png"},
  "High Knees": { muscle: "Legs", "type": "cardio", image: "/images/exercises/high-knees.png"},
  "Wrist Curls (with bottles/cans)": { muscle: "Forearms", "type": "strength", image: "/images/exercises/wrist-curls-bottles-cans.png"},
  "Burpees": { muscle: "Full Body", "type": "conditioning", image: "/images/exercises/burpees.png"},
  "Full Body Stretch": { muscle: "Full Body", "type": "flexibility", image: "/images/exercises/full-body-stretch.png"},
  "Easy Walking": { muscle: "Full Body", "type": "cardio", image: "/images/exercises/easy-walking.png"},
  "Alternating Lunges": { muscle: "Legs", "type": "strength", image: "/images/exercises/alternating-lunges.png"},
  "Plank Shoulder Taps": { muscle: "Core", "type": "strength", image: "/images/exercises/plank-shoulder-taps.png"},
  "Skater Hops": { muscle: "Legs", "type": "plyometrics", image: "/images/exercises/skater-hops.png"},
  "Side Lunges": { muscle: "Legs", "type": "strength", image: "/images/exercises/side-lunges.png"},
  "Butt Kicks": { muscle: "Legs", "type": "cardio", image: "/images/exercises/butt-kicks.png"},
  "Resistance Band Pull-Aparts": { muscle: "Shoulders", "type": "strength", image: "/images/exercises/resistance-band-pull-aparts.png"},
  "Yoga Routine": { muscle: "Full Body", "type": "flexibility", image: "/images/exercises/yoga-routine.png"},
  "Shuttle Ghosting": { muscle: "Full Body", "type": "agility", image: "/images/exercises/shuttle-ghosting.png"},
  "Jump Rope (imaginary)": { muscle: "Full Body", "type": "cardio", image: "/images/exercises/jump-rope-imaginary.png"},
  "Broad Jumps": { muscle: "Legs", "type": "plyometrics", image: "/images/exercises/broad-jumps.png"},
  "Tuck Jumps": { muscle: "Legs", "type": "plyometrics", image: "/images/exercises/tuck-jumps.png"},
  "Light Jog/Walk": { muscle: "Full Body", "type": "cardio", image: "/images/exercises/light-jog-walk.png"},
  "Power Cleans (if trained)": { muscle: "Full Body", "type": "power", image: "/images/exercises/power-cleans-if-trained.png"},
  "Cone Sprints (Short Distance)": { muscle: "Full Body", "type": "agility", image: "/images/exercises/cone-sprints-short-distance.png"},
  "Treadmill Sprint Intervals": { muscle: "Full Body", "type": "cardio", image: "/images/exercises/treadmill-sprint-intervals.png"},
  "Rowing Machine": { muscle: "Full Body", "type": "cardio", image: "/images/exercises/rowing-machine.png"},
  "Foam Rolling & Stretch": { muscle: "Full Body", "type": "flexibility", image: "/images/exercises/foam-rolling-stretch.png"},
  "Romanian Deadlifts (Dumbbells)": { muscle: "Hamstrings", "type": "strength", image: "/images/exercises/romanian-deadlifts-dumbbells.png"},
  "Cable Kickbacks": { muscle: "Glutes", "type": "strength", image: "/images/exercises/cable-kickbacks.png"},
  "Cable Lateral Raises": { muscle: "Shoulders", "type": "strength", image: "/images/exercises/cable-lateral-raises.png"},
  "Lateral Hurdle Hops": { muscle: "Legs", "type": "plyometrics", image: "/images/exercises/lateral-hurdle-hops.png"},
  "Rowing Machine Sprint": { muscle: "Full Body", "type": "cardio", image: "/images/exercises/rowing-machine-sprint.png"},
  "Light Elliptical / Walk": { muscle: "Full Body", "type": "cardio", image: "/images/exercises/light-elliptical-walk.png"}
};