import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Separator } from '@/components/ui/separator';
import { parseWeeklyWorkoutPlan, type DailyWorkout } from '@/lib/workout-parser';
import { Dumbbell, Repeat, Timer } from 'lucide-react';

const emojiMap: { [key: string]: string } = {
  squats: '🦵',
  'push-ups': '💪',
  lunges: '🦵',
  plank: '🧘',
  deadlift: '🏋️',
  'bench press': '🏋️',
  'pull-ups': '💪',
  crunches: '🧘',
  burpees: '🥵',
  'jumping jacks': '🤸',
  'bicep curls': '💪',
  rest: '😴',
};

function getEmojiForExercise(name: string): string {
  const lowerCaseName = name.toLowerCase();
  for (const key in emojiMap) {
    if (lowerCaseName.includes(key)) {
      return emojiMap[key];
    }
  }
  return '🔥';
}

export function WorkoutCard({ plan }: { plan: string }) {
  const weeklyPlan: DailyWorkout[] = parseWeeklyWorkoutPlan(plan);

  if (weeklyPlan.length === 0) {
    return (
       <Card>
        <CardHeader>
          <CardTitle className="font-headline">Your Custom Workout Plan</CardTitle>
          <CardDescription>There was an issue parsing the workout plan. Please find the raw plan below.</CardDescription>
        </CardHeader>
        <CardContent>
          <pre className="whitespace-pre-wrap font-body text-sm bg-secondary p-4 rounded-md">{plan}</pre>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="shadow-lg">
      <CardHeader>
        <CardTitle className="font-headline">Your Custom Weekly Workout Plan</CardTitle>
        <CardDescription>Here is your personalized 7-day workout plan generated by our AI trainer.</CardDescription>
      </CardHeader>
      <CardContent>
        <Accordion type="single" collapsible defaultValue="item-0">
          {weeklyPlan.map((day, dayIndex) => (
            <AccordionItem value={`item-${dayIndex}`} key={dayIndex}>
              <AccordionTrigger className="font-headline">{day.day}: {day.title}</AccordionTrigger>
              <AccordionContent>
                {day.exercises.length > 0 ? (
                  <div className="space-y-4 pt-2">
                    {day.exercises.map((exercise, exIndex) => (
                      <div key={exIndex}>
                        <div className="flex items-start gap-4">
                          <span className="text-2xl mt-1">{getEmojiForExercise(exercise.name)}</span>
                          <div className="flex-1">
                            <p className="font-semibold">{exercise.name}</p>
                            <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground mt-1">
                              <div className="flex items-center gap-1.5">
                                <Dumbbell className="h-4 w-4" />
                                <span>{exercise.sets} sets</span>
                              </div>
                              <div className="flex items-center gap-1.5">
                                <Repeat className="h-4 w-4" />
                                <span>{exercise.reps} reps</span>
                              </div>
                              <div className="flex items-center gap-1.5">
                                <Timer className="h-4 w-4" />
                                <span>{exercise.rest}</span>
                              </div>
                            </div>
                          </div>
                        </div>
                        {exIndex < day.exercises.length - 1 && <Separator className="mt-4" />}
                      </div>
                    ))}
                  </div>
                ) : (
                   <div className="flex items-center gap-4 p-4">
                     <span className="text-2xl">{getEmojiForExercise('rest')}</span>
                     <p className="font-semibold text-muted-foreground">Rest Day</p>
                   </div>
                )}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </CardContent>
    </Card>
  );
}
