import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { parseWorkoutPlan, type Exercise } from '@/lib/workout-parser';
import { Dumbbell, Repeat, Timer } from 'lucide-react';

const emojiMap: { [key: string]: string } = {
  squats: '🦵',
  push-ups: '💪',
  lunges: '🦵',
  plank: '🧘',
  deadlift: '🏋️',
  'bench press': '🏋️',
  pull-ups: '💪',
  crunches: '🧘',
  burpees: '🥵',
  'jumping jacks': '🤸',
  'bicep curls': '💪',
};

function getEmojiForExercise(name: string): string {
  const lowerCaseName = name.toLowerCase();
  for (const key in emojiMap) {
    if (lowerCaseName.includes(key)) {
      return emojiMap[key];
    }
  }
  return '🔥';
}


export function WorkoutCard({ plan }: { plan: string }) {
  const exercises = parseWorkoutPlan(plan);

  if (exercises.length === 0) {
    return (
       <Card>
        <CardHeader>
          <CardTitle className="font-headline">Your Custom Workout Plan</CardTitle>
          <CardDescription>There was an issue parsing the workout plan. Please find the raw plan below.</CardDescription>
        </CardHeader>
        <CardContent>
          <pre className="whitespace-pre-wrap font-body text-sm bg-secondary p-4 rounded-md">{plan}</pre>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card className="shadow-lg">
      <CardHeader>
        <CardTitle className="font-headline">Your Custom Workout Plan</CardTitle>
        <CardDescription>Here is the personalized workout plan generated by our AI trainer.</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {exercises.map((exercise, index) => (
            <div key={index}>
              <div className="flex items-start gap-4">
                 <span className="text-2xl mt-1">{getEmojiForExercise(exercise.name)}</span>
                <div className="flex-1">
                  <p className="font-semibold font-headline">{exercise.name}</p>
                  <div className="flex items-center gap-4 text-sm text-muted-foreground mt-1">
                    <div className="flex items-center gap-1.5">
                      <Dumbbell className="h-4 w-4" />
                      <span>{exercise.sets} sets</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <Repeat className="h-4 w-4" />
                      <span>{exercise.reps} reps</span>
                    </div>
                     <div className="flex items-center gap-1.5">
                      <Timer className="h-4 w-4" />
                      <span>{exercise.rest}</span>
                    </div>
                  </div>
                </div>
              </div>
              {index < exercises.length - 1 && <Separator className="mt-4" />}
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
