

'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Separator } from '@/components/ui/separator';
import { parseWeeklyWorkoutPlan, type DailyWorkout } from '@/lib/workout-parser';
import { Dumbbell, Repeat, Timer, PlayCircle, Save, Trash2 } from 'lucide-react';
import { Button } from './ui/button';
import { ActiveWorkoutDialog } from './active-workout-dialog';
import { useToast } from '@/hooks/use-toast';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from './ui/alert-dialog';
import { useLocalStorage } from '@/hooks/use-local-storage';

const emojiMap: { [key: string]: string } = {
  squats: '🦵',
  'push-ups': '💪',
  lunges: '🦵',
  plank: '🧘',
  deadlift: '🏋️',
  'bench press': '🏋️',
  'pull-ups': '💪',
  crunches: '🧘',
  burpees: '🥵',
  'jumping jacks': '🤸',
  'bicep curls': '💪',
  rest: '😴',
};

function getEmojiForExercise(name: string): string {
  const lowerCaseName = name.toLowerCase();
  for (const key in emojiMap) {
    if (lowerCaseName.includes(key)) {
      return emojiMap[key];
    }
  }
  return '🔥';
}

interface WorkoutCardProps {
    plan: string;
    showActions?: boolean;
    onDelete?: () => void;
}

export function WorkoutCard({ plan, showActions = false, onDelete }: WorkoutCardProps) {
  const [isWorkoutDialogOpen, setWorkoutDialogOpen] = useState(false);
  const [selectedWorkout, setSelectedWorkout] = useState<DailyWorkout | null>(null);
  const { toast } = useToast();
  const [savedWorkouts, setSavedWorkouts] = useLocalStorage<any[]>('saved-ai-workouts', []);

  const weeklyPlan: DailyWorkout[] = parseWeeklyWorkoutPlan(plan);

  const handleStartWorkout = (day: DailyWorkout) => {
    setSelectedWorkout(day);
    setWorkoutDialogOpen(true);
  };
  
  const handleSaveWorkout = () => {
    const isAlreadySaved = savedWorkouts.some(workout => workout.plan === plan);
    if(isAlreadySaved) {
         toast({
            variant: 'destructive',
            title: 'Already Saved',
            description: 'This workout plan is already in your saved list.',
        });
        return;
    }

    const newWorkout = {
      id: new Date().toISOString(),
      name: `Custom Workout - ${new Date().toLocaleDateString()}`,
      plan: plan,
    };
    setSavedWorkouts([...savedWorkouts, newWorkout]);
    toast({
      title: 'Workout Saved!',
      description: 'Your custom workout plan has been saved to your device.',
    });
  }
  
  const handleDeleteWorkout = () => {
    if (onDelete) {
        onDelete();
        toast({
            variant: 'destructive',
            title: 'Workout Discarded',
            description: 'The generated workout plan has been discarded.',
        });
    }
  }


  if (weeklyPlan.length === 0) {
    return (
       <Card>
        <CardHeader>
          <CardTitle className="font-headline">Your Custom Workout Plan</CardTitle>
          <CardDescription>There was an issue parsing the workout plan. Please find the raw plan below.</CardDescription>
        </CardHeader>
        <CardContent>
          <pre className="whitespace-pre-wrap font-body text-sm bg-secondary p-4 rounded-md">{plan}</pre>
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="font-headline">Your Custom Weekly Workout Plan</CardTitle>
          <CardDescription>Here is your personalized 7-day workout plan generated by our AI trainer.</CardDescription>
        </CardHeader>
        <CardContent>
          <Accordion type="single" collapsible defaultValue="item-0">
            {weeklyPlan.map((day, dayIndex) => (
              <AccordionItem value={`item-${dayIndex}`} key={dayIndex}>
                <AccordionTrigger className="font-headline">{day.day}: {day.title}</AccordionTrigger>
                <AccordionContent>
                  {day.exercises.length > 0 ? (
                    <div className="space-y-4 pt-2">
                      {day.exercises.map((exercise, exIndex) => (
                        <div key={exIndex}>
                          <div className="flex items-start gap-4">
                            <span className="text-2xl mt-1">{getEmojiForExercise(exercise.name)}</span>
                            <div className="flex-1">
                              <p className="font-semibold">{exercise.name}</p>
                              <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground mt-1">
                                <div className="flex items-center gap-1.5">
                                  <Dumbbell className="h-4 w-4" />
                                  <span>{exercise.sets} sets</span>
                                </div>
                                <div className="flex items-center gap-1.5">
                                  <Repeat className="h-4 w-4" />
                                  <span>{exercise.reps} reps</span>
                                </div>
                                <div className="flex items-center gap-1.5">
                                  <Timer className="h-4 w-4" />
                                  <span>{exercise.rest}</span>
                                </div>
                              </div>
                            </div>
                          </div>
                          {exIndex < day.exercises.length - 1 && <Separator className="mt-4" />}
                        </div>
                      ))}
                       <div className="mt-6">
                          <Button onClick={() => handleStartWorkout(day)}>
                            <PlayCircle className="mr-2 h-4 w-4" />
                            Start Workout
                          </Button>
                        </div>
                    </div>
                  ) : (
                     <div className="flex items-center gap-4 p-4">
                       <span className="text-2xl">{getEmojiForExercise('rest')}</span>
                       <p className="font-semibold text-muted-foreground">Rest Day</p>
                     </div>
                  )}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </CardContent>
        {showActions && (
          <CardFooter className="flex justify-end gap-2">
            <AlertDialog>
                <AlertDialogTrigger asChild>
                    <Button variant="outline">
                        <Trash2 className="mr-2 h-4 w-4" />
                        Discard
                    </Button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                    <AlertDialogHeader>
                    <AlertDialogTitle>Are you sure?</AlertDialogTitle>
                    <AlertDialogDescription>
                        This will discard the generated workout plan. This action cannot be undone.
                    </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction onClick={handleDeleteWorkout}>Discard</AlertDialogAction>
                    </AlertDialogFooter>
                </AlertDialogContent>
            </AlertDialog>
            <Button onClick={handleSaveWorkout}>
              <Save className="mr-2 h-4 w-4" />
              Save Workout
            </Button>
          </CardFooter>
        )}
      </Card>
      <ActiveWorkoutDialog 
        isOpen={isWorkoutDialogOpen}
        onOpenChange={setWorkoutDialogOpen}
        workout={selectedWorkout}
      />
    </>
  );
}
