import Link from 'next/link';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Dumbbell, Calculator, UtensilsCrossed, PersonStanding, TrendingUp, Sparkles } from 'lucide-react';

const features = [
  {
    title: 'AI Workout Planner',
    description: 'Get a personalized workout plan generated by AI.',
    href: '/dashboard/athlete-workout-planner',
    icon: <Sparkles className="h-8 w-8 text-primary" />,
  },
  {
    title: 'Calculators',
    description: 'Calculate your BMI and daily calorie needs.',
    href: '/dashboard/calculators',
    icon: <Calculator className="h-8 w-8 text-primary" />,
  },
  {
    title: 'General Workouts',
    description: 'Browse our library of pre-defined workout plans.',
    href: '/dashboard/general-workouts',
    icon: <Dumbbell className="h-8 w-8 text-primary" />,
  },
  {
    title: 'Nutrition Plans',
    description: 'Find the perfect meal plan for your goals.',
    href: '/dashboard/nutrition',
    icon: <UtensilsCrossed className="h-8 w-8 text-primary" />,
  },
  {
    title: 'Posing Tutorials',
    description: 'Master the art of physique presentation.',
    href: '/dashboard/posing-tutorials',
    icon: <PersonStanding className="h-8 w-8 text-primary" />,
  },
  {
    title: 'Track Progress',
    description: 'Monitor your gains and stay motivated.',
    href: '/dashboard/progress',
    icon: <TrendingUp className="h-8 w-8 text-primary" />,
  },
];

export default function DashboardPage() {
  return (
    <div className="flex flex-col gap-8">
      <div>
        <h1 className="text-3xl font-bold font-headline">Welcome, Freak!</h1>
        <p className="text-muted-foreground">Ready to crush your goals today?</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {features.map((feature) => (
          <Link href={feature.href} key={feature.title}>
            <Card className="h-full hover:border-primary transition-all duration-300 hover:shadow-lg">
              <CardHeader className="flex flex-row items-center gap-4">
                {feature.icon}
                <CardTitle className="font-headline">{feature.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">{feature.description}</p>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>
    </div>
  );
}
