
'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Dumbbell, Calculator, UtensilsCrossed, PersonStanding, TrendingUp, Sparkles, ListPlus, BookOpen } from 'lucide-react';

const features = [
  {
    title: 'AI Workout Planner',
    description: 'Get a personalized workout plan generated by AI.',
    href: '/dashboard/athlete-workout-planner',
    icon: <Sparkles className="h-8 w-8 text-primary" />,
  },
  {
    title: 'My Customized Plans',
    description: 'Create and manage your own custom workout plans.',
    href: '/dashboard/my-plans',
    icon: <ListPlus className="h-8 w-8 text-primary" />,
  },
   {
    title: 'Exercise Library',
    description: 'Browse hundreds of exercises with animated examples.',
    href: '/dashboard/exercise-library',
    icon: <BookOpen className="h-8 w-8 text-primary" />,
  },
  {
    title: 'General Workouts',
    description: 'Browse our library of pre-defined workout plans.',
    href: '/dashboard/general-workouts',
    icon: <Dumbbell className="h-8 w-8 text-primary" />,
  },
  {
    title: 'Calculators',
    description: 'Calculate your BMI and daily calorie needs.',
    href: '/dashboard/calculators',
    icon: <Calculator className="h-8 w-8 text-primary" />,
  },
  {
    title: 'Nutrition Plans',
    description: 'Find the perfect meal plan for your goals.',
    href: '/dashboard/nutrition',
    icon: <UtensilsCrossed className="h-8 w-8 text-primary" />,
  },
  {
    title: 'Posing Tutorials',
    description: 'Master the art of physique presentation.',
    href: '/dashboard/posing-tutorials',
    icon: <PersonStanding className="h-8 w-8 text-primary" />,
  },
  {
    title: 'Track Progress',
    description: 'Monitor your gains and stay motivated.',
    href: '/dashboard/progress',
    icon: <TrendingUp className="h-8 w-8 text-primary" />,
  },
];

export default function DashboardPage() {
  return (
    <div className="flex flex-col gap-8">
      <div>
        <motion.h1 
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-3xl font-bold font-headline">Welcome, Freak!</motion.h1>
        <motion.p 
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="text-muted-foreground">Ready to crush your goals today?</motion.p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {features.map((feature, i) => (
          <motion.div
            key={feature.title}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 * i }}
          >
            <Link href={feature.href} >
                <motion.div
                whileHover={{ scale: 1.05, rotateY: 3 }}
                transition={{ type: "spring", stiffness: 300 }}
                className="h-full"
                >
                <Card className="h-full hover:border-primary transition-all duration-300 hover:shadow-lg">
                    <CardHeader className="flex flex-row items-center gap-4">
                    {feature.icon}
                    <CardTitle className="font-headline">{feature.title}</CardTitle>
                    </CardHeader>
                    <CardContent>
                    <p className="text-muted-foreground">{feature.description}</p>
                    </CardContent>
                </Card>
                </motion.div>
            </Link>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
